# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Building Code
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git branch
      - run: npm ci
      - run: npm install
      - run: apt install zsh 
      - name: Print github
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$GITHUB_CONTEXT" && echo "$JOB_CONTEXT"
      - run: npm run build --if-present
      - run: ls -alh
      - run: rm -rf node_modules && mv public public_unused && mv dist public
      - run: zip -rv Archive.zip *
      - run: npm run push-new-theme:uk
      
