name: Release production
on:
  push:
    tags:
      - v*
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    uses: ./.github/workflows/lint.yml

  call-build:
    uses: ./.github/workflows/build.yml
    needs: call-lint
    with:
      release_stage: production
      tag: ${{ github.ref_name }}
      prefix: eve

  call-localise:
    uses: ./.github/workflows/localise.yml
    needs: [call-lint, call-build]
    with:
      stores: '["uk", "ie", "fr", "ie-staging"]'
    secrets:
      uk_password: ${{ secrets.SHOPIFY_UK_API_PASSWORD }}
      ie_password: ${{ secrets.SHOPIFY_IE_API_PASSWORD }}
      fr_password: ${{ secrets.SHOPIFY_FR_API_PASSWORD }}
      ie_staging_password: ${{ secrets.SHOPIFY_IE_STAGING_API_PASSWORD }}

  call-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: call-localise
    secrets:
      uk_password: ${{ secrets.SHOPIFY_UK_API_PASSWORD }}
      ie_password: ${{ secrets.SHOPIFY_IE_API_PASSWORD }}
      fr_password: ${{ secrets.SHOPIFY_FR_API_PASSWORD }}
      ie_staging_password: ${{ secrets.SHOPIFY_IE_STAGING_API_PASSWORD }}
      ngrok_token: ${{ secrets.NGROK_AUTH_TOKEN }}

  clean-up:
    runs-on: ubuntu-latest
    needs: call-deploy
    steps:
      - name: Delete base theme
        uses: geekyeggo/delete-artifact@v1
        with:
          name: base-theme
          failOnError: false
